# Generated by Django 4.2.5 on 2023-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
